# Generated by Django 5.2.12 on 2026-04-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0002_subscriber_category_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
